PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/6d5cda1db88da11c3dc7df549098890d5e840683

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/904a602c74dc08a100b5c2bd490807de19e73e10) in current PX4/master (aa80167b476957f546a33b4626752958e9d30518)
https://github.com/PX4/NuttX/compare/904a602c74dc08a100b5c2bd490807de19e73e10...6d5cda1db88da11c3dc7df549098890d5e840683

6d5cda1db8 (HEAD, origin/master) Fix nxstyle warning
4ebf446ebb arm/sama5: Fix error: chip/sam_ehci.c:340:38: error: statement with no effect
bb8c4485a2 libc: Change OK/ERROR macro to enum
6637c5a0b9 nrf52 PWM: fix missing trailing comma (build failure)
2ce0dfffaf nrf52 ADC: pass configuration struct as const
cbab6b79da nrf52 ADC: minor fixes
87dff7c69a Fix nxstyle warning
b236b82328 Add 2.4 Inch TFT LCD Shield ILI9341 for nucleo-l152re, 8080 MCU 8-bit bus interface I
5dabb4c2d8 sched/sched/sched_waitpid.c: Fix return value
68ff96c242 fix comment to match with #define

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/e066cd177ca7f2703625a56b744deaa1d7045301

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/909eff540d8004371d5838b9c0764cc753d665cf) in current PX4/master (aa80167b476957f546a33b4626752958e9d30518)
https://github.com/PX4/NuttX-apps/compare/909eff540d8004371d5838b9c0764cc753d665cf...e066cd177ca7f2703625a56b744deaa1d7045301

e066cd17 (HEAD -> master, origin/master) examples/pwm: fix style issue found in CI
37c8e548 examples/pwm: fix help message
fe915679 style/Document: remove unnecessary trailing whitespace
b5692d80 style/code: remove unnecessary trailing whitespace
d64929d7 Fix nxstyle warning
12a5a5cc examples: Ignore the default action if app call sigwait
b506600c irtest: use global arrays instead of __attributes__((section)) organization
1fcf43b5 graphics/twm4nx/apps/ccalibration.cxx: Fix syslog formats
e1a7c253 testing/getprime/getprime_main.c: Fix a comment
ec0f0b7f system/nxrecorder/nxrecorder.c: Fix a syslog format